---
- hosts: dev
  gather_facts: no
  tasks:
  - name: delete the folder
    file:
      path: /tmp/devops
      state: directory
  - name: creating a folder
    file:
     path: /tmp/devops
     state: directory
  - name: copying war file
    copy:
     src: /{{test}}/gameoflife-1.0.0.war
     dest: /tmp/devops/gameoflife-1.0.0.war
     mode: 0777
  - name: executing war file
    shell: "cd /tmp/devops/; nohup java -jar gameoflife-1.0.0.war &"
    become: true
